dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
env:
  - TENSORFLOW_VERSION=1.10.0
  - TENSORFLOW_VERSION=1.10.1
  - TENSORFLOW_VERSION=1.11.0
  - TENSORFLOW_VERSION=1.12.2
  - TENSORFLOW_VERSION=1.13.1
install:
  - pip install tensorflow==$TENSORFLOW_VERSION
  - pip install .
# command to run tests
script: pytest