from .abstract_machine import Machine, AutoregressiveMachine, DirectSamplingMachine
from .simple_conv_net_autoregressive_1D import SimpleConvNetAutoregressive1D
from .conv_net_autoregressive_2D import ConvNetAutoregressive2D
